# conda env create --file environment.yml
name: ecommerce_analytics
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - pip
  - pyprojroot
  - python=3.10
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - joblib
  - matplotlib
  - seaborn
  - plotly
  - statsmodels
  - ipython
  - sqlalchemy
  - pip:
    - pyhere
